name: .NET

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # we have to use a larger runner because the default windows runner 
        # only comes with 14GB working disk which we well and truly fill now.
        # part of the problem is that git keeps a copy of all lfs files in the
        # index as well as rehydrated in the repo which effectively double the size.
        os: [ubuntu-latest, windows-latest-larger, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # https://github.com/nschloe/action-cached-lfs-checkout
      - name: Checkout code
        uses: nschloe/action-cached-lfs-checkout@v1.2.5
      - name: Get drive info
        shell: pwsh
        run: Get-PSDrive
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test (macOS)
        if: startsWith(matrix.os, 'macos-')
        timeout-minutes: 30
        run: |
          ulimit -n 65536
          mkdir -p ./artifacts
          dotnet test ./test/Emu.Tests/Emu.Tests.csproj --no-build --blame-hang --blame-hang-timeout 10m --diag ./artifacts/test-macos-diag.log
      - name: Test
        if: startsWith(matrix.os, 'ubuntu-') || startsWith(matrix.os, 'windows-')
        run: dotnet test --no-build
  automerge:
    # https://github.com/marketplace/actions/github-action-merge-dependabot
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
